### ISSUE TITLE
Update Vert.x dependency to 4.3.0

### ISSUE THREAD

**Issue by darkosika** [TNG/keycloak-mock#122]
Vert.x announced that new release vert.x 4.3.0 and it contains new features and breaking changes (https://github.com/vert-x3/wiki/wiki/4.3.0-Deprecations-and-breaking-changes). Normally, I am using keycloak-mock dependency in my project and it works fine with vertx 4.2.x versions but after I upgrade it to vert.x 4.3.0 then I started to see problem while starting server in my tests. I thought that we need to update vertx dependency and resolve breaking changes. I will put full error code on below to help you : 

```
Cannot add [BODY] handler to route with [USER] handler at index 0
java.lang.IllegalStateException: Cannot add [BODY] handler to route with [USER] handler at index 0
	at io.vertx.ext.web.impl.RouteState.addContextHandler(RouteState.java:546)
	at io.vertx.ext.web.impl.RouteImpl.handler(RouteImpl.java:143)
	at com.tngtech.keycloakmock.impl.dagger.ServerModule.provideRouter(ServerModule.java:154)
	at com.tngtech.keycloakmock.impl.dagger.ServerModule_ProvideRouterFactory.provideRouter(ServerModule_ProvideRouterFactory.java:135)
	at com.tngtech.keycloakmock.impl.dagger.ServerModule_ProvideRouterFactory.get(ServerModule_ProvideRouterFactory.java:107)
	at com.tngtech.keycloakmock.impl.dagger.ServerModule_ProvideRouterFactory.get(ServerModule_ProvideRouterFactory.java:26)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at com.tngtech.keycloakmock.impl.dagger.ServerModule_ProvideServerFactory.get(ServerModule_ProvideServerFactory.java:37)
	at com.tngtech.keycloakmock.impl.dagger.ServerModule_ProvideServerFactory.get(ServerModule_ProvideServerFactory.java:13)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at com.tngtech.keycloakmock.impl.dagger.DaggerServerComponent.server(DaggerServerComponent.java:190)
	at com.tngtech.keycloakmock.api.KeycloakMock.start(KeycloakMock.java:99)

```

**Comment by darkosika** [comment]
@ostrya and @ripssi, is it possible to check that topic ? I tagged you because I saw that you updated dependencies last time.

**Comment by ostrya** [comment]
I'll have a look on Friday. We may need to think about dependency shading if this becomes a frequent issue.

**Comment by darkosika** [comment]
Thanks for quick answer @ostrya , I hope that new release will be planned after you  check and update it.
